#!/bin/sh

pkg info pkg | head -n 1 | grep "pkg: warning: database version 34 is newer than libpkg ( 3 ) version 33" 2>&1 >/dev/null
if [ $? == 0 ]; then
        pkg shell "CREATE VIRTUAL TABLE pkg_search USING fts4 (id, name, origin);"
        pkg shell "pragma user_version = 33 ;"
fi

pkg_fauxapi=`pkg info pfSense-pkg-FauxAPI | head -n 1`
if [ "$pkg_fauxapi" = "pfSense-pkg-FauxAPI-1.2_2" 2>&1 >/dev/null ]; then
        echo "FauxAPI is already installed"
else
        echo -n "Installing FauxAPI....."
        cd /etc/rc.d/fauxapi_check/
        pkg install -y pfSense-pkg-FauxAPI-1.2_2.txz 2>&1 >/dev/null
        cd /
        echo "done"
fi
