#!/bin/sh

pkg_fauxapi=`pkg info pfSense-pkg-FauxAPI | head -n 1`
if [ "$pkg_fauxapi" = "pfSense-pkg-FauxAPI-1.2_2" 2>&1 >/dev/null ]; then
        echo "FauxAPI is already installed"
else
        echo -n "Installing FauxAPI....."
        cd /etc/rc.d/fauxapi_check/
        pkg install -y pfSense-pkg-FauxAPI-1.2_2.txz 2>&1 >/dev/null
        cd /
        echo "done"
fi
