#!/bin/sh

pkg info pkg | head -n 1 | grep "pkg: warning: database version 34 is newer than libpkg ( 3 ) version 33" 2>&1 >/dev/null
if [ $? == 0 ]; then
        pkg shell "CREATE VIRTUAL TABLE pkg_search USING fts4 (id, name, origin);"
        pkg shell "pragma user_version = 33 ;"
fi
		
pkg_base=`pkg info AISense-base | head -n 1 | cut -c1-12`
if [ "$pkg_base" = "AISense-base" 2>&1 >/dev/null ]; then
	echo "AISense Base package is already installed"
else
	echo -n "Installing AISense Base package....."
	pkg install -y AISense-base 2>&1 >/dev/null
	echo "done"
fi
