#!/bin/sh

pkg info pkg | head -n 1 | grep "pkg: warning: database version 34 is newer than libpkg ( 3 ) version 33" 2>&1 >/dev/null
if [ $? == 0 ]; then
        pkg shell "CREATE VIRTUAL TABLE pkg_search USING fts4 (id, name, origin);"
        pkg shell "pragma user_version = 33 ;"
fi

pkg_nasm=`pkg info nasm | head -n 1 | cut -c1-4`
if [ "$pkg_nasm" = "nasm" 2>&1 >/dev/null ]; then
        echo "nasm is already installed"
else
        echo -n "Installing nasm....."
        pkg install -y nasm 2>&1 >/dev/null
        echo "done"
fi

pkg_binutils=`pkg info binutils | head -n 1 | cut -c1-8`
if [ "$pkg_binutils" = "binutils" 2>&1 >/dev/null ]; then
        echo -n "binutils is already installed"
else
        echo "Installing binutils....."
        pkg install -y binutils 2>&1 >/dev/null
        echo "done"
fi
