#!/bin/sh

pkg_snort=`pkg info AISense-pkg-snort| head -n 1 | cut -c1-17`
if [ "$pkg_snort" = "AISense-pkg-snort" 2>&1 >/dev/null ]; then
        echo "Snort is already installed"
else
        echo -n "Installing Snort....."
        pkg install -y AISense-pkg-snort 2>&1 >/dev/null
        echo "done"
fi
